import "~/styles/globals.css";
import { signIn, auth } from "@/auth";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  if (!session) {
    return (
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <form
            action={async () => {
              "use server";
              await signIn("google");
            }}
          >
            <button type="submit">Signin with Google</button>
          </form>
        </body>
      </html>
    );
  }
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <head>
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </head>
      <body className="h-screen w-screen">{children}</body>
    </html>
  );
}
